projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('recipes.urls')),  # /
    # path('recipes/', include('recipes.urls')), # /recipes
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'
urlpatterns = [
    path("", views.home, name="home"),
    path("recipes/<int:id>", views.recipe, name="recipe"),
    path("recipes/category/<int:category_id>/", views.category, name="category"),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here 
# cada model, representa uma tabela no banco de dados.
class Category(models.Model):
    name = models.CharField(max_length=65)
    def __str__(self):
        return self.name
    
class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug  = models.SlugField() # slug indexado
    prepararion_time = models.IntegerField()
    prepararion_time_unit = models.CharField(max_length=65)
    prepararion_steps = models.TextField()
    prepararion_steps_is_html = models.BooleanField(default=False)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    created_at = models.DateTimeField(auto_now_add=True) #gera uma data no momento da criacao e nao mexe mais nela 
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%d/%m/%Y/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )
    def __str__(self):
        return self.title

class Blog (models.Model):
     title = models.CharField(max_length=65)
     text = models.CharField(max_length=165)
     data_create = models.DateTimeField(auto_now_add=True)
     date_up = models.DateTimeField(auto_now=True)
     author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
     url_img = models.ImageField()
     

recipes/views.py
from django.http import HttpResponse
from django.shortcuts import render

from utils.recipes.factory import make_recipe  # importando a function

from .models import Recipe


# 
def home(resquest):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    return render(resquest, 'recipes/pages/home.html', context={
        'recipes': recipes
    })
def category(resquest, category_id):
    recipes = Recipe.objects.filter(
        category__id = category_id
        ).order_by('-id')
    return render(resquest, 'recipes/pages/home.html', context={
        'recipes': recipes
    })

def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': make_recipe(),
        'is_datail_page': True
    })

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %} 
{% block title %}Home |{% endblock title %}

{% block content %}
  <div class="main-content main-content-list container">
      {% for recipe in recipes %}
        {%include 'recipes/partials/recipe.html'%} 
      {% endfor %}
    
  </div>
{% endblock content %}


recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}
{% block title %} |{% endblock title %}
 
{% block content %}
<div class="main-content main-content-detail container">
  {%include 'recipes/partials/recipe.html'%}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://wisleyaraujo.github.io/" target="_blank" rel=" noreferrernoopener">Wisley Araujo</a>
  </div>
  <div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">DJango</a>
  </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %} {% comment %} link {% endcomment %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
  integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
  integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
  integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap"
  rel="stylesheet"
/>

<link rel="stylesheet" href="{% static 'recipes/css/style.css' %}" />
{% comment %} <link rel="stylesheet" href="{% static 'global/css/global-style.css' %}" /> {% endcomment %}
{% comment %} link {% endcomment %}
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
  <div class="main-header container">
    <h1>
      <a class="main-logo" href="/">
        <i class="fas fa-utensils main-logo-icon"></i> 
        <span class="main-logo-title">Recipes</span> <!-- ICON -->
      </a>
    </h1>
  </div>
</header>   

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
  {% if recipe.cover %}
    <div class="recipe-list-cover">
      <img src="{{recipe.cover.url}}" alt="" />
    </div>
  {% endif %}

  <div class="recipe-title-container">
    <h2 class="recipe-title">{{recipe.title}}</h2>
  </div>

  <div class="recipe-autor">
    <span class="recipe-autor-item">
      <i class="fas fa-user"></i>
      {% if recipe.author.first_name %} 
        {{recipe.author.first_name}}
        {{recipe.author.last_name}} 
      {% else %} 
        {{recipe.author.username}} 
      {%endif%}
    </span>
    <span class="recipe-autor-item">
      <i class="fas fa-calendar-alt"></i>
      {{recipe.created_at}}
    </span>
    <span class="recipe-autor-item">
      <a href="{% url 'recipes:category' recipe.category.id %}">
        <i class="fa fa-layer-group"></i>
        <span>{{recipe.category.name}}</span>
      </a>
    </span>
  </div>

  <div class="recipe-content">
    <p>{{recipe.description}}</p>
  </div>

  <div class="recipe-meta-container">
    <div class="recipe-meta recipe-meta-preparation">
      <h3 class="recipe-meta-title">
        Preparo
        <i class="fas fa-stopwatch"></i>
      </h3>
      <div class="recipe-meta-text">
        {{recipe.prepararion_time}}{{recipe.prepararion_time_unit}}
      </div>
    </div>
    <div class="recipe-meta recipe-servings">
      <h3 class="recipe-meta-title">
        <i class="fas fa-pizza-slice"></i>
        Porcoes
      </h3>
      <div class="recipe-meta-text">
        {{recipe.servings}}{{recipe.servings_unit}}
      </div>
    </div>
  </div>

  {% if is_datail_page is not True %}
    <footer class="recipe-footer">
      <a
        href="recipes/3"
        class="recipe-read-more button button-dark button-full-width"
      >
        <i class="fa fa-eye"></i>
        <span>ver mais...</span>
      </a>
    </footer>
  {% endif %} 

  {% if is_datail_page is True %}
    <div class="preparation-steps">{{recipe.prepartation_steps}}</div>
  {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
  <div class="container">
    <form class="search-form">
      <input type="search" class="search-input" name="search" />
      <button type="submit" class="search-button">
        <i class="fas fa-search"></i>
      </button>
    </form>
  </div>
</div>